### ISSUE TITLE
Resize company logo image

### ISSUE THREAD

**Issue by jeremy-jameson** [technology-toolbox/techtoolbox-hugo#44]
This issue was reported by [Lighthouse](https://developers.google.com/web/tools/lighthouse) when selecting the **Mobile** device option:

![image](https://user-images.githubusercontent.com/1385288/142620012-212f676f-c7f7-489b-a553-604873a275c0.png)

Lighthouse recommends a _larger_ image (i.e. "Expected size: 400 x 90").

Note the company logo image is resized using the following CSS rules:

```CSS
a.navbar-brand {
  max-width: 200px;
}

@media (min-width: 576px) {
  a.navbar-brand {
    max-width: 220px;
  }
}
```
